############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Me"
url = "about/"
weight = 2

[[main]]
name = "Translation & Editing"
url = "translation-and-editing/"
weight = 3

[[main]]
name = "Publications"
url = "publications/"
weight = 5

# tech editing dropdown
[[main]]
weight = 4
name = "Tech Editing"

[[main]]
parent = "Tech Editing"
name = "Services"
weight = 1
pageRef = "/services"

[[main]]
parent = "Tech Editing"
name = "Working with Me"
weight = 2
pageRef = "/working-with-me"

# footer menu

[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About Me"
url = "about/"
weight = 2

[[footer]]
name = "Translation & Editing"
url = "translation-and-editing/"
weight = 3

[[footer]]
name = "Services"
weight = 4
pageRef = "/services"

[[footer]]
name = "Working with Me"
weight = 5
pageRef = "/working-with-me"

[[footer]]
name = "Publications"
url = "publications/"
weight = 6

[[footer]]
name = "Newsletter"
url = "https://yarnboundtales.substack.com/"
weight = 7

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 8