############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Me"
url = "about/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 4

[[main]]
name = "Gallery"
url = "gallery/"
weight = 5

# tech editing dropdown
[[main]]
weight = 3
name = "Tech Editing"

[[main]]
parent = "Tech Editing"
name = "Services"
weight = 1
pageRef = "/services"

[[main]]
parent = "Tech Editing"
name = "Working with Me"
weight = 2
pageRef = "/process"

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
