############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Me"
url = "about/"
weight = 2

[[main]]
name = "Translation & Editing"
url = "translation-and-editing/"
weight = 3

[[main]]
name = "Technical Editing"
weight = 4

[[main]]
parent = "Technical Editing"
name = "Info"
url = "technical-editing/"
weight = 1

[[main]]
parent = "Technical Editing"
name = "Portfolio"
url = "te-portfolio/"
weight = 2

[[main]]
parent = "Technical Editing"
name = "My Knitting Projects"
url = "my-knitting-projects/"
weight = 3

[[main]]
name = "Publications"
url = "publications/"
weight = 5



# footer menu

[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About Me"
url = "about/"
weight = 2

[[footer]]
name = "Translation & Editing"
url = "translation-and-editing/"
weight = 3

[[footer]]
name = "Technical Editing"
url = "technical-editing/"
weight = 4

[[footer]]
name = "Publications"
url = "publications/"
weight = 5

[[footer]]
name = "Portfolio"
url = "te-portfolio/"
weight = 6

[[footer]]
name = "My Knitting Projects"
url = "my-knitting-projects/"
weight = 7

[[footer]]
name = "Newsletter"
url = "https://yarnboundtales.substack.com/"
weight = 8

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 9

[[footer]]
name = "Impressum"
url = "impressum/"
weight = 10